---
# tasks file for mariadb
- name: "mariadb-server installation"
  yum:
   name: "mariadb-server,MySQL-python"
   state: "installed"
- name: "start mariadb service"
  service:
   name: "mariadb"
   state: "started"
   enabled: yes
- name: "mediawiki database"
  mysql_db:
   name: "{{mediawiki_db_name}}"
   state: present
- name: "mediawiki user+privileges"
  mysql_user:
   name: "{{mediawiki_db_user}}"
   password: "{{mediawiki_db_password}}"
   priv: "{{mediawiki_db_name}}.*:ALL"
   host: "{{item}}"
   state: present
  with_items: "localhost"