version: "2"

services:

    db:

        image: mysql:latest

        command: --default-authentication-plugin=mysql_native_password

        ports:

            - "3306:3306"

        environment:

            MYSQL_DATABASE: drupal

            MYSQL_USER: user

            MYSQL_PASSWORD: test

            MYSQL_ROOT_PASSWORD: test

        volumes:

            - ./dump:/docker-entrypoint-initdb.d

            - /var/lib/mysql

        networks:

            - default

    phpmyadmin:

        image: phpmyadmin/phpmyadmin

        links:

            - db:db

        ports:

            - 8000:80

        environment:

            PMA_HOST: db

            MYSQL_USER: user

            MYSQL_PASSWORD: test

            MYSQL_ROOT_PASSWORD: test


