# Clone le dépôt du robot dans le dépertoire de pi.
- name: "CLONE ROBOT REPOSITORY"
  hosts: "raspberry"
  roles:
    - role: "roles/robotgitlab"

# Start the robot every minute by adding a cron job.
- name: "ADD CRON JOB TO START ROBOT"
  hosts: "raspberry"
  roles:
    - role: "roles/robotcron"

# Installer tmux et ajouter ma commande robot.
- name: "INSTALL TMUX & SETUP IT"
  hosts: "raspberry"
  roles:
    - role: "roles/robottmux"

