- name: "Check firewall state"
  command: "systemctl is-active firewalld"
  register: state_firewalld
  ignore_errors: yes
#- debug: var=state_firewalld.stdout_lines[0]
- name: "Start firewalld"
  service:
   name: "firewalld"
   state: "restarted"
   enabled: yes
  when: state_firewalld.stdout_lines[0] != "active"
- name: "Open port for http (80)"
  firewalld: 
   service: "http"
   state: "enabled" 
   permanent: yes 
   immediate: yes
- name: "Open port for mysql"
  firewalld:
   service: "mysql"
   state: "enabled" 
   permanent: yes 
   immediate: yes