- name: "Apache installation"
  hosts: apache
  handlers:
   - name: "Restart apache service"
     service:
      name: "httpd"
      state: "restarted"
 tasks:
   - name: "Apache package installation" 
     yum:
      name: "httpd"
      state: "present"
   - name: "Apache configuration"
     template: 
      src: "inventory.conf.j2"
      dest: "/etc/httpd/conf.d/inventory.conf"
      owner: "apache"
      group: "apache"
     # notify apache restart handler 
     notify: ["Restart apache service"] 
   - name: "Start apache service"
     service:
      name: "httpd"
      state: "started" 
      enabled: yes

