---
# tasks file for container
- name: "Create containers"
  docker_container:
   name: "{{inventory_hostname}}"
   hostname: "{{inventory_hostname}}"
   networks:
    - name: "{{network_name}}"
   image: "{{docker_image|d('centos/systemd')}}"
   volumes: ['/run','/sys/fs/cgroup']
   privileged: yes
   state: started