- name: "Table count"
  hosts: mysql
  gather_facts: no
  tasks:
    - name: "Retrive table count"
      mysql_request:
       db_name: "mediawiki"
       request: "{{lookup('file', 'test.sql')}}"
      register: result
    - debug: var=result