# Install tmux just for monitoring robot.
- name: "Install tmux just to see robot status"
  apt:
    name: tmux
    state: "present"

# Copy my tmux configuration to hide status bar.
- name: "Copy my tmux configuration to hide status bar"
  copy:
    src: files/.tmux.conf
    dest: /home/pi

#A dd robot command to /usr/bin.
- name: "Add robot command to /usr/bin for monitoring"
  copy:
    src: files/robot.sh
    dest: /usr/bin/robot
    owner: pi
    mode: a+x
